# These hyperparameters were chosen based on the paper:
# "DeepTCR is a deep learning framework for revealing sequence concepts within T-cell repertoires"

seq_model_hyperparams:
  num_features: [ 32, 64, 128 ]
  dropout: 0.0
  batch_norm: False
  embedding_dim: 64
  encoder:
    kernel: [ 5, 3, 3 ]
    stride: [ 1, 3, 3 ]
    num_layers: 3
    activation: leakyrelu
  decoder:
    kernel: [ 3, 3 ]  # omit last, as last kernel size is calculated
    stride: [ 2, 2 ]  # omit last, as last stride is calculated
    initial_feature: 64
    initial_len: 4
    num_layers: 3
    activation: relu

use_vdj: True
vdj_embedding_dim: 48
vdj_dec_layers: [ 128, 64 ]

use_embedding_matrix: True
dec_hdim: [ 128, 256 ]
enc_hdim: [ 256, 256 ]
zdim: 256

# Loss and optimizer
lr: 1.0e-3
batch_size: 10000

loss_weights:
  - 1.0
  - 1.0
  - 1.0e-3