# These parameters are just dummy values for setting up the yaml file

seq_model_arch: Transformer
seq_model_hyperparams:
  num_tokens: 23
  embedding_size: 64
  num_heads: 4
  forward_expansion: 4
  encoding_layers: 6
  decoding_layers: 6
  dropout: 0.1

scRNA_model_arch: MLP
scRNA_model_hyperparams:
  gene_hidden:
    - 800
  activation: leakyrelu
  output_activation: relu
  dropout: 0.2
  batch_norm: True

# shared param by all models, "interface" between the models
hdim: 800

# params of shared encoder and decoder
activation: leakyrelu
dropout: 0.2
batch_norm: True
shared_hidden:
  - 200
zdim: 100

# Loss and optimizer
lr: 3.0e-4
batch_size: 256
losses:
  - MSE
  - CE

loss_weights:
  - 0.1
  - 1.0
  - 0.00005